package:
  name: libnl3-cli-cos6-x86_64
  version: 3.2.21

source:
  - url: https://vault.centos.org/6.10/os/x86_64/Packages/libnl3-cli-3.2.21-8.el6.x86_64.rpm
    sha256: 61d423be78139bd7db2e8c904468126be68394ec6b321f2cc48c3ba310d5fd92
    no_hoist: true
    folder: binary
  # - url: http://vault.centos.org/6.10/os/Source/SPackages/libnl3-3.2.21-8.el6.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int }}
  noarch: generic
  binary_relocation: False
  detect_binary_files_with_prefix: False
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - libnl3-cos6-x86_64 ==3.2.21 *_{{ cdt_build_number|int }}
  host:
    - libnl3-cos6-x86_64 ==3.2.21 *_{{ cdt_build_number|int }}
  run:
    - libnl3-cos6-x86_64 ==3.2.21 *_{{ cdt_build_number|int }}
  run_constrained:
    - sysroot_linux-64 ==99999999999

test:
  commands:
    - echo "it installs!"

about:
  home: http://www.infradead.org/~tgr/libnl/
  license: LGPLv2
  license_family: LGPL
  license_file: {{ SRC_DIR }}/binary/usr/share/doc/libnl3-cli-3.2.21/COPYING
  summary: "(CDT) Command line interface utils for libnl3"
  description: |
        This package contains various libnl3 utils and additional libraries on which
        they depend

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
