package:
  name: libpng-cos7-aarch64
  version: 1.5.13

source:
  - url: http://mirror.centos.org/altarch/7/os/aarch64/Packages/libpng-1.5.13-8.el7.aarch64.rpm
    sha256: a132cbe0d407be884e14691031a9a613160577446b8297b378391f943f0ceff0
    no_hoist: true
    folder: binary
  # - url: http://vault.centos.org/7.7.1908/os/Source/SPackages/libpng-1.5.13-8.el7.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int }}
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false
  missing_dso_whitelist:
    - '*'

requirements:
  run_constrained:
    - sysroot_linux-aarch64 ==99999999999

test:
  commands:
    - echo "it installs!"

about:
  home: http://www.libpng.org/pub/png/
  license: zlib
  license_family: Other
  license_file: libpng-license
  summary: (CDT) A library of functions for manipulating PNG image format files
  description: |
    The libpng package contains a library of functions for creating and
    manipulating PNG (Portable Network Graphics) image format files.  PNG is a
    bit-mapped graphics format similar to the GIF format.  PNG was created to
    replace the GIF format, since GIF uses a patented data compression algorithm.
    Libpng should be installed if you need to manipulate PNG format image files.

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
