package:
  name: libtiff-cos6-x86_64
  version: 3.9.4

source:
  - url: https://vault.centos.org/6.10/os/x86_64/Packages/libtiff-3.9.4-21.el6_8.x86_64.rpm
    sha256: 882756e964228ec72fc7bd4df910cb48519bfa844419d8134325883356603997
    no_hoist: true
    folder: binary
  # - url: http://vault.centos.org/6.10/os/Source/SPackages/libtiff-3.9.4-21.el6_8.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int }}
  noarch: generic
  binary_relocation: False
  detect_binary_files_with_prefix: False
  missing_dso_whitelist:
    - '*'

requirements:
  run_constrained:
    - sysroot_linux-64 ==99999999999

test:
  commands:
    - echo "it installs!"

about:
  home: http://www.remotesensing.org/libtiff/
  license: libtiff
  license_family: Other
  license_file: {{ SRC_DIR }}/binary/usr/share/doc/libtiff-3.9.4/COPYRIGHT
  summary: "(CDT) Library of functions for manipulating TIFF format image files"
  description: |
        The libtiff package contains a library of functions for manipulating TIFF
        (Tagged Image File Format) image format files.  TIFF is a widely used file
        format for bitmapped images.  TIFF files usually end in the .tif extension and
        they are often quite large.  The libtiff package should be installed if you
        need to manipulate TIFF format image files.

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
