package:
  name: expat-cos7-ppc64le
  version: 2.1.0

source:
  - url: http://mirror.centos.org/altarch/7/os/ppc64le/Packages/expat-2.1.0-12.el7.ppc64le.rpm
    sha256: 00893d45ac1ffacb782fdfe82d28106d9df5d202a0daf10a3dea1fcede70fcf2
    no_hoist: true
    folder: binary
  # - url: http://vault.centos.org/7.7.1908/os/Source/SPackages/expat-2.1.0-12.el7.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int }}
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false
  missing_dso_whitelist:
    - '*'

requirements:
  run_constrained:
    - sysroot_linux-ppc64le ==99999999999

test:
  commands:
    - echo "it installs!"

about:
  home: http://www.libexpat.org/
  license: MIT
  license_family: MIT
  license_file: expat-license
  summary: (CDT) An XML parser library
  description: |
    This is expat, the C library for parsing XML, written by James Clark. Expat is
    a stream oriented XML parser. This means that you register handlers with the
    parser prior to starting the parse. These handlers are called when the parser
    discovers the associated structures in the document being parsed. A start tag
    is an example of the kind of structures for which you may register handlers.

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
