package:
  name: libxrandr-cos7-ppc64le
  version: 1.5.1

source:
  - url: http://mirror.centos.org/altarch/7/os/ppc64le/Packages/libXrandr-1.5.1-2.el7.ppc64le.rpm
    sha256: ec45fc8ae470c0a025b7c38621ce529e41d188379f3985a6eacab356fb9e5122
    no_hoist: true
    folder: binary
  # - url: http://vault.centos.org/7.7.1908/os/Source/SPackages/libXrandr-1.5.1-2.el7.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int }}
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - libx11-cos7-ppc64le >=1.6.0 *_{{ cdt_build_number|int }}
  host:
    - libx11-cos7-ppc64le >=1.6.0 *_{{ cdt_build_number|int }}
  run:
    - libx11-cos7-ppc64le >=1.6.0 *_{{ cdt_build_number|int }}
  run_constrained:
    - sysroot_linux-ppc64le ==99999999999

test:
  commands:
    - echo "it installs!"

about:
  home: http://www.x.org
  license: MIT
  license_family: MIT
  license_file: libxrandr-license
  summary: (CDT) X.Org X11 libXrandr runtime library
  description: |
    X.Org X11 libXrandr runtime library

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
