package:
  name: at-spi-cos6-x86_64
  version: 1.28.1

source:
  - url: https://vault.centos.org/6.10/os/x86_64/Packages/at-spi-1.28.1-2.el6.centos.x86_64.rpm
    sha256: fd951cd7fd7bd1533b2c1f5d16c213d0406a5edbddf49e1405650a946998a9fa
    no_hoist: true
    folder: binary
  # - url: http://vault.centos.org/6.10/os/Source/SPackages/at-spi-1.28.1-2.el6.centos.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int }}
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - orbit2-cos6-x86_64 >=2.6.0 *_{{ cdt_build_number|int }}
    - atk-cos6-x86_64 >=1.13.0 *_{{ cdt_build_number|int }}
    - gail-cos6-x86_64 >=2.24.23 *_{{ cdt_build_number|int }}
    - gtk2-cos6-x86_64 >=2.10.0 *_{{ cdt_build_number|int }}
    - libbonobo-cos6-x86_64 >=2.4.0 *_{{ cdt_build_number|int }}
  host:
    - orbit2-cos6-x86_64 >=2.6.0 *_{{ cdt_build_number|int }}
    - atk-cos6-x86_64 >=1.13.0 *_{{ cdt_build_number|int }}
    - gail-cos6-x86_64 >=2.24.23 *_{{ cdt_build_number|int }}
    - gtk2-cos6-x86_64 >=2.10.0 *_{{ cdt_build_number|int }}
    - libbonobo-cos6-x86_64 >=2.4.0 *_{{ cdt_build_number|int }}
  run:
    - orbit2-cos6-x86_64 >=2.6.0 *_{{ cdt_build_number|int }}
    - atk-cos6-x86_64 >=1.13.0 *_{{ cdt_build_number|int }}
    - gail-cos6-x86_64 >=2.24.23 *_{{ cdt_build_number|int }}
    - gtk2-cos6-x86_64 >=2.10.0 *_{{ cdt_build_number|int }}
    - libbonobo-cos6-x86_64 >=2.4.0 *_{{ cdt_build_number|int }}
  run_constrained:
    - sysroot_linux-64 ==99999999999

test:
  commands:
    - echo "it installs!"

about:
  home: http://developer.gnome.org/projects/gap/
  license: LGPL-2.0-or-later
  license_family: LGPL
  license_file: at-spi-license
  summary: (CDT) Assistive Technology Service Provider Interface
  description: |
    at-spi allows assistive technologies to access GTK-based applications.
    Essentially it exposes the internals of applications for automation, so tools
    such as screen readers, magnifiers, or even scripting interfaces can query and
    interact with GUI controls.

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
