package:
  name: glib2-cos6-x86_64
  version: 2.28.8

source:
  - url: https://vault.centos.org/6.10/os/x86_64/Packages/glib2-2.28.8-10.el6.x86_64.rpm
    sha256: a3945f3e6ee7c6fc8dd11a4f39641a8df6af818198e0a45a1f73f4753f6bd34c
    no_hoist: true
    folder: binary
  # - url: http://vault.centos.org/6.10/os/Source/SPackages/glib2-2.28.8-10.el6.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int }}
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false
  missing_dso_whitelist:
    - '*'

requirements:
  run_constrained:
    - sysroot_linux-64 ==99999999999

test:
  commands:
    - echo "it installs!"

about:
  home: http://www.gtk.org
  license: LGPL-2.0-or-later
  license_family: LGPL
  license_file: glib2-copying
  summary: (CDT) A library of handy utility functions
  description: |
    GLib is the low-level core library that forms the basis for projects such as
    GTK+ and GNOME. It provides data structure handling for C, portability
    wrappers, and interfaces for such runtime functionality as an event loop,
    threads, dynamic loading, and an object system.

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
