package:
  name: libselinux-conda-x86_64
  version: 3.5

source:
  - url: https://vault.almalinux.org/9.3/BaseOS/x86_64/os/Packages/libselinux-3.5-1.el9.x86_64.rpm
    sha256: 061602b6e2738a2fdc5b4e99f3d6d1a04c6c80c9bf80c109cde31c69f5530379
    no_hoist: true
    folder: binary
  # - url: https://vault.almalinux.org/9.3/BaseOS/Source/Packages/libselinux-3.5-1.el9.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int + 1000 }}
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - libsepol-conda-x86_64 >=3.5 *_{{ cdt_build_number|int + 1000 }}
  host:
    - libsepol-conda-x86_64 >=3.5 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-64 2.34.*
  run:
    - libsepol-conda-x86_64 >=3.5 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-64 2.34.*

test:
  commands:
    - echo "it installs!"

about:
  home: https://github.com/SELinuxProject/selinux/wiki
  license: Public-Domain
  license_family: Public-Domain
  summary: (CDT) SELinux library and simple utilities
  description: |
    Security-enhanced Linux is a feature of the Linux® kernel and a number of
    utilities with enhanced security functionality designed to add mandatory
    access controls to Linux.  The Security-enhanced Linux kernel contains new
    architectural components originally developed to improve the security of the
    Flask operating system. These architectural components provide general support
    for the enforcement of many kinds of mandatory access control policies,
    including those based on the concepts of Type Enforcement®, Role-based Access
    Control, and Multi-level Security.  libselinux provides an API for SELinux
    applications to get and set process and file security contexts and to obtain
    security policy decisions.  Required for any applications that use the SELinux
    API.

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
