package:
  name: libnl3-cos6-x86_64
  version: 3.2.21

source:
  - url: https://vault.centos.org/6.10/os/x86_64/Packages/libnl3-3.2.21-8.el6.x86_64.rpm
    sha256: 4728e70d63f7c0248d4c9a42b77cd1ec3f383d468cbe69b5532508fbe4de4d45
    no_hoist: true
    folder: binary
  # - url: http://vault.centos.org/6.10/os/Source/SPackages/libnl3-3.2.21-8.el6.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int }}
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false
  missing_dso_whitelist:
    - '*'

requirements:
  run_constrained:
    - sysroot_linux-64 ==99999999999

test:
  commands:
    - echo "it installs!"

about:
  home: http://www.infradead.org/~tgr/libnl/
  license: LGPLv2
  license_family: LGPL
  license_file: libnl3-license
  summary: (CDT) Convenience library for kernel netlink sockets
  description: |
    This package contains a convenience library to simplify using the Linux
    kernel's netlink sockets interface for network manipulation

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
