package:
  name: java-1.7.0-openjdk-headless-cos7-aarch64
  version: 1.7.0.261

source:
  - url: https://vault.centos.org/altarch/7.9.2009/os/aarch64/Packages/java-1.7.0-openjdk-headless-1.7.0.261-2.6.22.2.el7_8.aarch64.rpm
    sha256: a8de10493e86973aa3251d8fdc268b8a1dd7e9e79c563835506b7ee1a008e50d
    no_hoist: true
    folder: binary
  # - url: http://vault.centos.org/altarch/7.9.2009/os/Source/SPackages/java-1.7.0-openjdk-1.7.0.261-2.6.22.2.el7_8.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int + 1000 }}
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - chkconfig-cos7-aarch64 >=1.7 *_{{ cdt_build_number|int + 1000 }}
    - chkconfig-cos7-aarch64 >=1.7 *_{{ cdt_build_number|int + 1000 }}
    - copy-jdk-configs-cos7-aarch64 >=3.3 *_{{ cdt_build_number|int + 1000 }}
    - javapackages-tools-cos7-aarch64 >=3.4.1 *_{{ cdt_build_number|int + 1000 }}
    - nss-cos7-aarch64 >=3.44.0 *_{{ cdt_build_number|int + 1000 }}
    - nss-softokn-cos7-aarch64 >=3.44.0 *_{{ cdt_build_number|int + 1000 }}
  host:
    - chkconfig-cos7-aarch64 >=1.7 *_{{ cdt_build_number|int + 1000 }}
    - chkconfig-cos7-aarch64 >=1.7 *_{{ cdt_build_number|int + 1000 }}
    - copy-jdk-configs-cos7-aarch64 >=3.3 *_{{ cdt_build_number|int + 1000 }}
    - javapackages-tools-cos7-aarch64 >=3.4.1 *_{{ cdt_build_number|int + 1000 }}
    - nss-cos7-aarch64 >=3.44.0 *_{{ cdt_build_number|int + 1000 }}
    - nss-softokn-cos7-aarch64 >=3.44.0 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-aarch64 2.17.*
  run:
    - chkconfig-cos7-aarch64 >=1.7 *_{{ cdt_build_number|int + 1000 }}
    - chkconfig-cos7-aarch64 >=1.7 *_{{ cdt_build_number|int + 1000 }}
    - copy-jdk-configs-cos7-aarch64 >=3.3 *_{{ cdt_build_number|int + 1000 }}
    - javapackages-tools-cos7-aarch64 >=3.4.1 *_{{ cdt_build_number|int + 1000 }}
    - nss-cos7-aarch64 >=3.44.0 *_{{ cdt_build_number|int + 1000 }}
    - nss-softokn-cos7-aarch64 >=3.44.0 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-aarch64 2.17.*
test:
  commands:
    - echo "it installs!"

about:
  home: http://openjdk.java.net/
  license: ASL 1.1 and ASL 2.0 and BSD and BSD with advertising and GPL+ and GPLv2 and GPLv2 with exceptions and IJG and LGPLv2+ and MIT and MPLv1.1 and MPLv2.0 and Public Domain and W3C and zlib
  license_family: GPL2
  license_file: {{ SRC_DIR }}/binary/usr/lib/jvm/java-1.7.0-openjdk-1.7.0.261-2.6.22.2.el7_8.aarch64/LICENSE
  summary: (CDT) The OpenJDK runtime environment without audio and video support
  description: |
    The OpenJDK runtime environment without audio and video

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
