package:
  name: centos-release-cos7-aarch64
  version: 7

source:
  - url: http://mirror.centos.org/altarch/7/os/aarch64/Packages/centos-release-7-9.2009.0.el7.centos.aarch64.rpm
    sha256: 0588cbe9e9b38367f4d5f2e24ecffc08d28c4f65ccf860f478688a832719ebe5
    no_hoist: true
    folder: binary
  # - url: http://vault.centos.org/7.7.1908/os/Source/SPackages/centos-release-7-9.2009.0.el7.centos.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int }}
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false
  missing_dso_whitelist:
    - '*'

requirements:
  run_constrained:
    - sysroot_linux-aarch64 ==99999999999

test:
  commands:
    - echo "it installs!"

about:
  home: centos-release-cos7-aarch64
  license: GPL-2.0-only
  license_family: GPL2
  license_file: centos-release-license
  summary: (CDT) CentOS Linux release file
  description: |
    CentOS Linux release files

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
