package:
  name: mesa-dri-drivers-cos7-ppc64le
  version: 18.3.4

source:
  - url: https://vault.centos.org/altarch/7.9.2009/os/ppc64le/Packages/mesa-dri-drivers-18.3.4-10.el7.ppc64le.rpm
    sha256: bf422da8148a6dea20fa7f47e746bd738dc24246a63fe9309d769af158f9c963
    no_hoist: true
    folder: binary
  # - url: http://vault.centos.org/altarch/7.9.2009/os/Source/SPackages/mesa-18.3.4-10.el7.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int + 1000 }}
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - libdrm-cos7-ppc64le >=2.4.83 *_{{ cdt_build_number|int + 1000 }}
  host:
    - libdrm-cos7-ppc64le >=2.4.83 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-ppc64le 2.17.*
  run:
    - libdrm-cos7-ppc64le >=2.4.83 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-ppc64le 2.17.*

test:
  commands:
    - echo "it installs!"

about:
  home: http://www.mesa3d.org
  license: MIT
  license_family: MIT
  license_file: mesa-license
  summary: (CDT) Mesa-based DRI drivers
  description: |
    Mesa-based DRI drivers.

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
