package:
  name: xcb-util-cos6-x86_64
  version: 0.4.0

source:
  - url: https://vault.centos.org/6.10/os/x86_64/Packages/xcb-util-0.4.0-2.2.el6.x86_64.rpm
    sha256: 2d69df814957a3a2b537767cc28f20505fa92dbb71079b055cdf3e282bd7e9bf
    no_hoist: true
    folder: binary
  # - url: http://vault.centos.org/6.10/os/Source/SPackages/xcb-util-0.4.0-2.2.el6.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int }}
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false
  missing_dso_whitelist:
    - '*'

requirements:
  run_constrained:
    - sysroot_linux-64 ==99999999999

test:
  commands:
    - echo "it installs!"

about:
  home: http://xcb.freedesktop.org
  license: MIT
  license_family: MIT
  license_file: xcb-util-license
  summary: (CDT) Convenience libraries sitting on top of libxcb
  description: |
    The xcb-util module provides a number of libraries which sit on top of libxcb,
    the core X protocol library, and some of the extension libraries. These
    experimental libraries provide convenience functions and interfaces which make
    the raw X protocol more usable. Some of the libraries also provide client-side
    code which is not strictly part of the X protocol but which have traditionally
    been provided by Xlib.

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
