package:
  name: mesa-libgl-devel-cos7-aarch64
  version: 18.3.4

source:
  - url: http://mirror.centos.org/altarch/7/os/aarch64/Packages/mesa-libGL-devel-18.3.4-10.el7.aarch64.rpm
    sha256: 4414f0b094fef1ec6e2ca623d2e06407f91bf76c0762003768f92383d2328c6c
    no_hoist: true
    folder: binary
  # - url: http://vault.centos.org/7.7.1908/os/Source/SPackages/mesa-18.3.4-10.el7.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int }}
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - mesa-khr-devel-cos7-aarch64 ==18.3.4 *_{{ cdt_build_number|int }}
    - mesa-libgl-cos7-aarch64 ==18.3.4 *_{{ cdt_build_number|int }}
  host:
    - mesa-khr-devel-cos7-aarch64 ==18.3.4 *_{{ cdt_build_number|int }}
    - mesa-libgl-cos7-aarch64 ==18.3.4 *_{{ cdt_build_number|int }}
  run:
    - mesa-khr-devel-cos7-aarch64 ==18.3.4 *_{{ cdt_build_number|int }}
    - mesa-libgl-cos7-aarch64 ==18.3.4 *_{{ cdt_build_number|int }}
  run_constrained:
    - sysroot_linux-aarch64 ==99999999999

test:
  commands:
    - echo "it installs!"

about:
  home: http://www.mesa3d.org
  license: MIT
  license_family: MIT
  license_file: mesa-license
  summary: (CDT) Mesa libGL development package
  description: |
    Mesa libGL development package

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
