package:
  name: kmod-libs-alma8-x86_64
  version: 25

source:
  - url: https://vault.almalinux.org/8.9/BaseOS/x86_64/os/Packages/kmod-libs-25-19.el8.x86_64.rpm
    sha256: 6d3e07aa304b286bf806d7d4f00bfd39dd99e816baae9f5d25c864f9b33c7c16
    no_hoist: true
    folder: binary
  # - url: https://vault.almalinux.org/8.9/BaseOS/Source/Packages/kmod-25-19.el8.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int + 1000 }}
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false
  missing_dso_whitelist:
    - '*'

requirements:
  host:
    - sysroot_linux-64 2.28.*
  run:
    - sysroot_linux-64 2.28.*

test:
  commands:
    - echo "it installs!"

about:
  home: http://git.kernel.org/?p=utils/kernel/kmod/kmod.git;a=summary
  license: LGPL-2.0-or-later
  license_family: LGPL
  license_file: kmod-copying
  summary: (CDT) Libraries to handle kernel module loading and unloading
  description: |
    The kmod-libs package provides runtime libraries for any application that
    wishes to load or unload Linux kernel modules from the running system.

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
