package:
  name: mesa-libgbm-conda-x86_64
  version: 23.1.4

source:
  - url: https://vault.almalinux.org/8.9/AppStream/x86_64/os/Packages/mesa-libgbm-23.1.4-1.el8.x86_64.rpm
    sha256: 844c07d9f8d1390af0b3b8177ed5fe28fecc6a5c95d4fb308e62033b82cd8d24
    no_hoist: true
    folder: binary
  # - url: https://vault.almalinux.org/8.9/AppStream/Source/Packages/mesa-23.1.4-1.el8.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int + 1000 }}
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false
  missing_dso_whitelist:
    - '*'

requirements:
  host:
    - sysroot_linux-64 2.28.*
  run:
    - sysroot_linux-64 2.28.*

test:
  commands:
    - echo "it installs!"

about:
  home: http://www.mesa3d.org
  license: MIT
  license_family: MIT
  license_file: mesa-license
  summary: (CDT) Mesa gbm runtime library
  description: |
    Mesa gbm runtime library.

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
