package:
  name: libsepol-devel-alma8-x86_64
  version: 2.9

source:
  - url: https://vault.almalinux.org/8.9/BaseOS/x86_64/os/Packages/libsepol-devel-2.9-3.el8.x86_64.rpm
    sha256: bf7296b0ec33968e01014c1b5097b51c085bf393e11574b85d194c0f5555c292
    no_hoist: true
    folder: binary
  # - url: https://vault.almalinux.org/8.9/BaseOS/Source/Packages/libsepol-2.9-3.el8.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int + 1000 }}
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - libsepol-alma8-x86_64 ==2.9 *_{{ cdt_build_number|int + 1000 }}
  host:
    - libsepol-alma8-x86_64 ==2.9 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-64 2.28.*
  run:
    - libsepol-alma8-x86_64 ==2.9 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-64 2.28.*

test:
  commands:
    - echo "it installs!"

about:
  home: https://github.com/SELinuxProject/selinux/wiki
  license: LGPL-2.0-or-later
  license_family: LGPL
  license_file: libsepol-license
  summary: (CDT) Header files and libraries used to build policy manipulation tools
  description: |
    The libsepol-devel package contains the libraries and header files needed for
    developing applications that manipulate binary policies.

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
