package:
  name: ca-certificates-cos7-aarch64
  version: 2020.2.41

source:
  - url: http://mirror.centos.org/altarch/7/os/aarch64/Packages/ca-certificates-2020.2.41-70.0.el7_8.noarch.rpm
    sha256: 1095e8edd8713c148159831eda79522d8eae5c52f1930b7a570a157f3ccf2fc2
    no_hoist: true
    folder: binary
  # - url: http://vault.centos.org/7.7.1908/os/Source/SPackages/ca-certificates-2020.2.41-70.0.el7_8.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int }}
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - p11-kit-cos7-aarch64 >=0.23.5 *_{{ cdt_build_number|int }}
    - p11-kit-trust-cos7-aarch64 >=0.23.5 *_{{ cdt_build_number|int }}
  host:
    - p11-kit-cos7-aarch64 >=0.23.5 *_{{ cdt_build_number|int }}
    - p11-kit-trust-cos7-aarch64 >=0.23.5 *_{{ cdt_build_number|int }}
  run:
    - p11-kit-cos7-aarch64 >=0.23.5 *_{{ cdt_build_number|int }}
    - p11-kit-trust-cos7-aarch64 >=0.23.5 *_{{ cdt_build_number|int }}
  run_constrained:
    - sysroot_linux-aarch64 ==99999999999

test:
  commands:
    - echo "it installs!"

about:
  home: http://www.mozilla.org/
  license: Public-Domain
  license_family: Public-Domain
  summary: (CDT) The Mozilla CA root certificate bundle
  description: |
    This package contains the set of CA certificates chosen by the Mozilla
    Foundation for use with the Internet PKI.

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
