package:
  name: pciutils-cos6-x86_64
  version: 3.1.10

source:
  - url: https://vault.centos.org/6.10/os/x86_64/Packages/pciutils-3.1.10-4.el6.x86_64.rpm
    sha256: 032d8139acdddb79dbc85e8908a4e47cf797d8dfb73b5667c8e97f4fe902254d
    no_hoist: true
    folder: binary
  # - url: http://vault.centos.org/6.10/os/Source/SPackages/pciutils-3.1.10-4.el6.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int + 1000 }}
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - pciutils-libs-cos6-x86_64 ==3.1.10 *_{{ cdt_build_number|int + 1000 }}
  host:
    - pciutils-libs-cos6-x86_64 ==3.1.10 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-64 2.12.*
  run:
    - pciutils-libs-cos6-x86_64 ==3.1.10 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-64 2.12.*

test:
  commands:
    - echo "it installs!"

about:
  home: http://atrey.karlin.mff.cuni.cz/~mj/pciutils.shtml
  license: GPL-2.0-or-later
  license_family: GPL2
  license_file: pciutils-license
  summary: (CDT) PCI bus related utilities
  description: |
    The pciutils package contains various utilities for inspecting and setting
    devices connected to the PCI bus. The utilities provided require kernel
    version 2.1.82 or newer (which support the /proc/bus/pci interface).

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
