package:
  name: xcb-util-renderutil-devel-cos6-x86_64
  version: 0.3.9

source:
  - url: https://vault.centos.org/6.10/os/x86_64/Packages/xcb-util-renderutil-devel-0.3.9-3.el6.x86_64.rpm
    sha256: 162143c451ce667249300db475041f18f15e25fd0c3e6163d77e400f466b7c9b
    no_hoist: true
    folder: binary
  # - url: http://vault.centos.org/6.10/os/Source/SPackages/xcb-util-renderutil-0.3.9-3.el6.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int }}
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - xcb-util-renderutil-cos6-x86_64 ==0.3.9 *_{{ cdt_build_number|int }}
  host:
    - xcb-util-renderutil-cos6-x86_64 ==0.3.9 *_{{ cdt_build_number|int }}
  run:
    - xcb-util-renderutil-cos6-x86_64 ==0.3.9 *_{{ cdt_build_number|int }}
  run_constrained:
    - sysroot_linux-64 ==99999999999

test:
  commands:
    - echo "it installs!"

about:
  home: http://xcb.freedesktop.org
  license: MIT
  license_family: MIT
  license_file: xcb-util-renderutil-license
  summary: (CDT) Development and header files for xcb-util-renderutil
  description: |
    Development files for xcb-util-renderutil.

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
