package:
  name: libglvnd-devel-cos7-x86_64
  version: 1.0.1

source:
  - url: http://vault.centos.org/7.9.2009/os/x86_64/Packages/libglvnd-devel-1.0.1-0.8.git5baa1e5.el7.x86_64.rpm
    sha256: f0a416c709982c68e52c8edca61390e837f4418cd021b576e286a2ff97ddd9f1
    no_hoist: true
    folder: binary
  # - url: http://vault.centos.org/7.9.2009/os/Source/SPackages/libglvnd-1.0.1-0.8.git5baa1e5.el7.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int + 1000 }}
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false
  missing_dso_whitelist:
    - '*'
  # this skip is here because we need different package hashes per distro.
  # we therefore list all possible values in CBC and skip those we don't want;
  # use in a selector ensures that the `distro` variable shows up in the hash
  skip: true  # [distro != "centos7"]

requirements:
  build:
    - libglvnd-cos7-x86_64 ==1.0.1 *_{{ cdt_build_number|int + 1000 }}
    - libglvnd-core-devel-cos7-x86_64 ==1.0.1 *_{{ cdt_build_number|int + 1000 }}
    - libglvnd-egl-cos7-x86_64 ==1.0.1 *_{{ cdt_build_number|int + 1000 }}
    - libglvnd-gles-cos7-x86_64 ==1.0.1 *_{{ cdt_build_number|int + 1000 }}
    - libglvnd-glx-cos7-x86_64 ==1.0.1 *_{{ cdt_build_number|int + 1000 }}
    - libglvnd-opengl-cos7-x86_64 ==1.0.1 *_{{ cdt_build_number|int + 1000 }}
  host:
    - libglvnd-cos7-x86_64 ==1.0.1 *_{{ cdt_build_number|int + 1000 }}
    - libglvnd-core-devel-cos7-x86_64 ==1.0.1 *_{{ cdt_build_number|int + 1000 }}
    - libglvnd-egl-cos7-x86_64 ==1.0.1 *_{{ cdt_build_number|int + 1000 }}
    - libglvnd-gles-cos7-x86_64 ==1.0.1 *_{{ cdt_build_number|int + 1000 }}
    - libglvnd-glx-cos7-x86_64 ==1.0.1 *_{{ cdt_build_number|int + 1000 }}
    - libglvnd-opengl-cos7-x86_64 ==1.0.1 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-64 2.17.*
  run:
    - libglvnd-cos7-x86_64 ==1.0.1 *_{{ cdt_build_number|int + 1000 }}
    - libglvnd-core-devel-cos7-x86_64 ==1.0.1 *_{{ cdt_build_number|int + 1000 }}
    - libglvnd-egl-cos7-x86_64 ==1.0.1 *_{{ cdt_build_number|int + 1000 }}
    - libglvnd-gles-cos7-x86_64 ==1.0.1 *_{{ cdt_build_number|int + 1000 }}
    - libglvnd-glx-cos7-x86_64 ==1.0.1 *_{{ cdt_build_number|int + 1000 }}
    - libglvnd-opengl-cos7-x86_64 ==1.0.1 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-64 2.17.*
test:
  commands:
    - echo "it installs!"

about:
  home: https://github.com/NVIDIA/libglvnd
  license: MIT
  license_family: MIT
  license_file: libglvnd-license
  summary: (CDT) Development files for libglvnd
  description: |
    The libglvnd-devel package contains libraries and header files for developing
    applications that use libglvnd.

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
