package:
  name: centos-release-cos7-ppc64le
  version: 7

source:
  - url: http://mirror.centos.org/altarch/7/os/ppc64le/Packages/centos-release-7-9.2009.0.el7.centos.ppc64le.rpm
    sha256: 9cc7d28e561100c8054b1ca7704f79ecdc80d08054b72b20ee7268c0b55b5ada
    no_hoist: true
    folder: binary
  # - url: http://vault.centos.org/7.7.1908/os/Source/SPackages/centos-release-7-9.2009.0.el7.centos.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int }}
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false
  missing_dso_whitelist:
    - '*'

requirements:
  run_constrained:
    - sysroot_linux-ppc64le ==99999999999

test:
  commands:
    - echo "it installs!"

about:
  home: centos-release-cos7-ppc64le
  license: GPL-2.0-only
  license_family: GPL2
  license_file: centos-release-license
  summary: (CDT) CentOS Linux release file
  description: |
    CentOS Linux release files

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
