package:
  name: pam-devel-cos7-ppc64le
  version: 1.1.8

source:
  - url: http://mirror.centos.org/altarch/7/os/ppc64le/Packages/pam-devel-1.1.8-23.el7.ppc64le.rpm
    sha256: 6b2bc3cc2e1fc3d590a9f8b1acc78cd6ad9704516ff81b15f2e1b57a51d94eb1
    no_hoist: true
    folder: binary
  # - url: http://vault.centos.org/7.7.1908/os/Source/SPackages/pam-1.1.8-23.el7.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int }}
  noarch: generic
  binary_relocation: False
  detect_binary_files_with_prefix: False
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - pam-cos7-ppc64le ==1.1.8 *_{{ cdt_build_number|int }}
  host:
    - pam-cos7-ppc64le ==1.1.8 *_{{ cdt_build_number|int }}
  run:
    - pam-cos7-ppc64le ==1.1.8 *_{{ cdt_build_number|int }}
  run_constrained:
    - sysroot_linux-ppc64le ==99999999999

test:
  commands:
    - echo "it installs!"

about:
  home: http://www.linux-pam.org/
  license: BSD and GPLv2+
  license_family: GPL2
  license_file: {{ SRC_DIR }}/binary/usr/share/doc/pam-devel-1.1.8/html/mwg-copyright.html
  summary: "(CDT) Files needed for developing PAM-aware applications and modules for PAM"
  description: |
        PAM (Pluggable Authentication Modules) is a system security tool that allows
        system administrators to set authentication policy without having to recompile
        programs that handle authentication. This package contains header files used
        for building both PAM-aware applications and modules for use with the PAM
        system.

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
