package:
  name: systemd-libs-cos7-ppc64le
  version: 219

source:
  - url: http://mirror.centos.org/altarch/7/os/ppc64le/Packages/systemd-libs-219-78.el7.ppc64le.rpm
    sha256: 36c17b0be3a5d20da7a48dd8992de7ad894a16c55d5be3f37269bff2c3047c32
    no_hoist: true
    folder: binary
  # - url: http://vault.centos.org/7.7.1908/os/Source/SPackages/systemd-219-78.el7.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int }}
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false
  missing_dso_whitelist:
    - '*'

requirements:
  run_constrained:
    - sysroot_linux-ppc64le ==99999999999

test:
  commands:
    - echo "it installs!"

about:
  home: http://www.freedesktop.org/wiki/Software/systemd
  license: LGPLv2+ and MIT
  license_family: LGPL
  license_file:
    - LICENSE.LGPL2.1
    - LICENSE.MIT
  summary: (CDT) systemd libraries
  description: |
    Libraries for systemd and udev, as well as the systemd PAM module.

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
