package:
  name: systemd-libs-cos7-aarch64
  version: 219

source:
  - url: http://mirror.centos.org/altarch/7/os/aarch64/Packages/systemd-libs-219-78.el7.aarch64.rpm
    sha256: 2d74cc808489701fcbaeb9311b6b3ed79af5aa41b7365bad31b3ce0d0aaa13fd
    no_hoist: true
    folder: binary
  # - url: http://vault.centos.org/7.7.1908/os/Source/SPackages/systemd-219-78.el7.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int + 1000 }}
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false
  missing_dso_whitelist:
    - '*'

requirements:
  host:
    - sysroot_linux-aarch64 2.17.*
  run:
    - sysroot_linux-aarch64 2.17.*

test:
  commands:
    - echo "it installs!"

about:
  home: http://www.freedesktop.org/wiki/Software/systemd
  license: LGPLv2+ and MIT
  license_family: LGPL
  license_file:
    - LICENSE.LGPL2.1
    - LICENSE.MIT
  summary: (CDT) systemd libraries
  description: |
    Libraries for systemd and udev, as well as the systemd PAM module.

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
