package:
  name: expat-cos7-x86_64
  version: 2.1.0

source:
  - url: http://mirror.centos.org/centos/7/os/x86_64/Packages/expat-2.1.0-12.el7.x86_64.rpm
    sha256: c73d74dee6c977bda30983111a290f054a8301797f32a20b550b4242679f057e
    no_hoist: true
    folder: binary
  # - url: http://vault.centos.org/7.7.1908/os/Source/SPackages/expat-2.1.0-12.el7.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int + 1000 }}
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false
  missing_dso_whitelist:
    - '*'

requirements:
  host:
    - sysroot_linux-64 2.17.*
  run:
    - sysroot_linux-64 2.17.*

test:
  commands:
    - echo "it installs!"

about:
  home: http://www.libexpat.org/
  license: MIT
  license_family: MIT
  license_file: expat-license
  summary: (CDT) An XML parser library
  description: |
    This is expat, the C library for parsing XML, written by James Clark. Expat is
    a stream oriented XML parser. This means that you register handlers with the
    parser prior to starting the parse. These handlers are called when the parser
    discovers the associated structures in the document being parsed. A start tag
    is an example of the kind of structures for which you may register handlers.

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
