package:
  name: systemd-devel-cos7-x86_64
  version: 219

source:
  - url: http://mirror.centos.org/centos/7/os/x86_64/Packages/systemd-devel-219-78.el7.x86_64.rpm
    sha256: 519610879aad1fb4b29c87a88c7e92e771707edf6bfe4a840f65c8fcd94904ef
    no_hoist: true
    folder: binary
  # - url: http://vault.centos.org/7.7.1908/os/Source/SPackages/systemd-219-78.el7.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int + 1000 }}
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - systemd-cos7-x86_64 ==219 *_{{ cdt_build_number|int + 1000 }}
    - systemd-libs-cos7-x86_64 ==219 *_{{ cdt_build_number|int + 1000 }}
  host:
    - systemd-cos7-x86_64 ==219 *_{{ cdt_build_number|int + 1000 }}
    - systemd-libs-cos7-x86_64 ==219 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-64 2.17.*
  run:
    - systemd-cos7-x86_64 ==219 *_{{ cdt_build_number|int + 1000 }}
    - systemd-libs-cos7-x86_64 ==219 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-64 2.17.*

test:
  commands:
    - echo "it installs!"

about:
  home: http://www.freedesktop.org/wiki/Software/systemd
  license: LGPLv2+ and MIT
  license_family: LGPL
  license_file:
    - LICENSE.GPL2
    - LICENSE.LGPL2.1
    - LICENSE.MIT
  summary: (CDT) Development headers for systemd
  description: |
    Development headers and auxiliary files for developing applications for
    systemd.

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
