package:
  name: libselinux-devel-alma8-x86_64
  version: 2.9

source:
  - url: https://vault.almalinux.org/8.9/BaseOS/x86_64/os/Packages/libselinux-devel-2.9-8.el8.x86_64.rpm
    sha256: d6e68c6171b3a8f0d99a91d5da5de2c15a518a1f0c2c5b7990c99f8c565d6e52
    no_hoist: true
    folder: binary
  # - url: https://vault.almalinux.org/8.9/BaseOS/Source/Packages/libselinux-2.9-8.el8.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int + 1000 }}
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - libselinux-alma8-x86_64 ==2.9 *_{{ cdt_build_number|int + 1000 }}
    - libsepol-devel-alma8-x86_64 >=2.9 *_{{ cdt_build_number|int + 1000 }}
  host:
    - libselinux-alma8-x86_64 ==2.9 *_{{ cdt_build_number|int + 1000 }}
    - libsepol-devel-alma8-x86_64 >=2.9 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-64 2.28.*
  run:
    - libselinux-alma8-x86_64 ==2.9 *_{{ cdt_build_number|int + 1000 }}
    - libsepol-devel-alma8-x86_64 >=2.9 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-64 2.28.*

test:
  commands:
    - echo "it installs!"

about:
  home: https://github.com/SELinuxProject/selinux/wiki
  license: Public-Domain
  license_family: Public-Domain
  summary: (CDT) Header files and libraries used to build SELinux
  description: |
    The libselinux-devel package contains the libraries and header files needed
    for developing SELinux applications.

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
