package:
  name: libibmad-cos6-x86_64
  version: 1.3.11

source:
  - url: https://vault.centos.org/6.10/os/x86_64/Packages/libibmad-1.3.11-1.el6.x86_64.rpm
    sha256: f80325873a4edb1495951967620f596bf839ba921670ff38bf231b0a4c1a4503
    no_hoist: true
    folder: binary
  # - url: http://vault.centos.org/6.10/os/Source/SPackages/libibmad-1.3.11-1.el6.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int }}
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false
  missing_dso_whitelist:
    - '*'

requirements:
  run_constrained:
    - sysroot_linux-64 ==99999999999

test:
  commands:
    - echo "it installs!"

about:
  home: http://openfabrics.org/
  license: GPLv2 or BSD
  license_family: GPL2
  license_file:
    - libibmad-license
  summary: (CDT) OpenFabrics Alliance InfiniBand MAD library
  description: |
    libibmad provides low layer IB functions for use by the IB diagnostic and
    management programs. These include MAD, SA, SMP, and other basic IB functions.

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
