package:
  name: audit-libs-devel-alma8-x86_64
  version: 3.0.7

source:
  - url: https://vault.almalinux.org/8.9/BaseOS/x86_64/os/Packages/audit-libs-devel-3.0.7-5.el8.x86_64.rpm
    sha256: 357e3d6d3fae2c8b214452fd6c4c8f279fb6a2643290a76f7d7535dbe40d037e
    no_hoist: true
    folder: binary
  # - url: https://vault.almalinux.org/8.9/BaseOS/Source/Packages/audit-3.0.7-5.el8.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int + 1000 }}
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - audit-libs-alma8-x86_64 ==3.0.7 *_{{ cdt_build_number|int + 1000 }}
    - kernel-headers-alma8-x86_64 >=2.6.29 *_{{ cdt_build_number|int + 1000 }}
  host:
    - audit-libs-alma8-x86_64 ==3.0.7 *_{{ cdt_build_number|int + 1000 }}
    - kernel-headers-alma8-x86_64 >=2.6.29 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-64 2.28.*
  run:
    - audit-libs-alma8-x86_64 ==3.0.7 *_{{ cdt_build_number|int + 1000 }}
    - kernel-headers-alma8-x86_64 >=2.6.29 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-64 2.28.*

test:
  commands:
    - echo "it installs!"

about:
  home: http://people.redhat.com/sgrubb/audit/
  license: LGPL-2.0-or-later
  license_family: LGPL
  license_file: audit-libs-copying.lib
  summary: (CDT) Header files for libaudit
  description: |
    The audit-libs-devel package contains the header files needed for developing
    applications that need to use the audit framework libraries.

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
