package:
  name: cracklib-dicts-cos7-ppc64le
  version: 2.9.0

source:
  - url: http://mirror.centos.org/altarch/7/os/ppc64le/Packages/cracklib-dicts-2.9.0-11.el7.ppc64le.rpm
    sha256: fa47851e58fdfe796378ec5ceaaf3bd03b6fe6284117bcb5f7e66d2b5943256b
    no_hoist: true
    folder: binary
  # - url: http://vault.centos.org/7.7.1908/os/Source/SPackages/cracklib-2.9.0-11.el7.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int }}
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - cracklib-cos7-ppc64le ==2.9.0 *_{{ cdt_build_number|int }}
  host:
    - cracklib-cos7-ppc64le ==2.9.0 *_{{ cdt_build_number|int }}
  run:
    - cracklib-cos7-ppc64le ==2.9.0 *_{{ cdt_build_number|int }}
  run_constrained:
    - sysroot_linux-ppc64le ==99999999999

test:
  commands:
    - echo "it installs!"

about:
  home: http://sourceforge.net/projects/cracklib/
  license: LGPL-2.0-or-later
  license_family: LGPL
  license_file: cracklib-copying.lib
  summary: (CDT) The standard CrackLib dictionaries
  description: |
    The cracklib-dicts package includes the CrackLib dictionaries. CrackLib will
    need to use the dictionary appropriate to your system, which is normally put
    in /usr/share/dict/words. Cracklib-dicts also contains the utilities necessary
    for the creation of new dictionaries.  If you are installing CrackLib, you
    should also install cracklib-dicts.

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
