package:
  name: glib2-cos7-ppc64le
  version: 2.56.1

source:
  - url: http://mirror.centos.org/altarch/7/os/ppc64le/Packages/glib2-2.56.1-7.el7.ppc64le.rpm
    sha256: 2936bfd4ed1c58bd682976cc45e66ca81c3a69a4886b495214b972730695eb64
    no_hoist: true
    folder: binary
  # - url: http://vault.centos.org/7.7.1908/os/Source/SPackages/glib2-2.56.1-7.el7.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int + 1000 }}
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false
  missing_dso_whitelist:
    - '*'

requirements:
  host:
    - sysroot_linux-ppc64le 2.17.*
  run:
    - sysroot_linux-ppc64le 2.17.*

test:
  commands:
    - echo "it installs!"

about:
  home: http://www.gtk.org
  license: LGPL-2.0-or-later
  license_family: LGPL
  license_file: glib2-copying
  summary: (CDT) A library of handy utility functions
  description: |
    GLib is the low-level core library that forms the basis for projects such as
    GTK+ and GNOME. It provides data structure handling for C, portability
    wrappers, and interfaces for such runtime functionality as an event loop,
    threads, dynamic loading, and an object system.

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
