package:
  name: libpng-devel-cos7-ppc64le
  version: 1.5.13

source:
  - url: http://mirror.centos.org/altarch/7/os/ppc64le/Packages/libpng-devel-1.5.13-8.el7.ppc64le.rpm
    sha256: 182598680db4f70865daad0bd79fe0ea76458d0f3674b7d8441a386aa5ead218
    no_hoist: true
    folder: binary
  # - url: http://vault.centos.org/7.7.1908/os/Source/SPackages/libpng-1.5.13-8.el7.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int }}
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - libpng-cos7-ppc64le ==1.5.13 *_{{ cdt_build_number|int }}
  host:
    - libpng-cos7-ppc64le ==1.5.13 *_{{ cdt_build_number|int }}
  run:
    - libpng-cos7-ppc64le ==1.5.13 *_{{ cdt_build_number|int }}
  run_constrained:
    - sysroot_linux-ppc64le ==99999999999

test:
  commands:
    - echo "it installs!"

about:
  home: http://www.libpng.org/pub/png/
  license: zlib
  license_family: Other
  license_file: libpng-license
  summary: (CDT) Development tools for programs to manipulate PNG image format files
  description: |
    The libpng-devel package contains header files and documentation necessary for
    developing programs using the PNG (Portable Network Graphics) library.  If you
    want to develop programs which will manipulate PNG image format files, you
    should install libpng-devel.  You'll also need to install the libpng package.

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
