package:
  name: numactl-devel-cos7-aarch64
  version: 2.0.12

source:
  - url: http://mirror.centos.org/altarch/7/os/aarch64/Packages/numactl-devel-2.0.12-5.el7.aarch64.rpm
    sha256: c9cf116e115f9a6560fbfb89ff741782b77c0cf4fa9488560608cc5e321609c8
    no_hoist: true
    folder: binary
  # - url: http://vault.centos.org/7.7.1908/os/Source/SPackages/numactl-2.0.12-5.el7.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int }}
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - numactl-libs-cos7-aarch64 ==2.0.12 *_{{ cdt_build_number|int }}
  host:
    - numactl-libs-cos7-aarch64 ==2.0.12 *_{{ cdt_build_number|int }}
  run:
    - numactl-libs-cos7-aarch64 ==2.0.12 *_{{ cdt_build_number|int }}
  run_constrained:
    - sysroot_linux-aarch64 ==99999999999

test:
  commands:
    - echo "it installs!"

about:
  home: https://github.com/numactl/numactl
  license: LGPLv2 and GPLv2
  license_family: GPL2
  license_file:
    - numactl-copyright.txt
    - numactl-gpl2.txt
    - numactl-lgpl2.txt
  summary: (CDT) Development package for building Applications that use numa
  description: |
    Provides development headers for numa library calls

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
