package:
  name: libnl3-devel-cos7-ppc64le
  version: 3.2.28

source:
  - url: http://mirror.centos.org/altarch/7/os/ppc64le/Packages/libnl3-devel-3.2.28-4.el7.ppc64le.rpm
    sha256: e810a2920d6e28348b5eb3f942b607d21d1378acee183ea883ec68971b13a0a7
    no_hoist: true
    folder: binary
  # - url: http://vault.centos.org/7.7.1908/os/Source/SPackages/libnl3-3.2.28-4.el7.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int }}
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - libnl3-cos7-ppc64le ==3.2.28 *_{{ cdt_build_number|int }}
    - libnl3-cli-cos7-ppc64le ==3.2.28 *_{{ cdt_build_number|int }}
  host:
    - libnl3-cos7-ppc64le ==3.2.28 *_{{ cdt_build_number|int }}
    - libnl3-cli-cos7-ppc64le ==3.2.28 *_{{ cdt_build_number|int }}
  run:
    - libnl3-cos7-ppc64le ==3.2.28 *_{{ cdt_build_number|int }}
    - libnl3-cli-cos7-ppc64le ==3.2.28 *_{{ cdt_build_number|int }}
  run_constrained:
    - sysroot_linux-ppc64le ==99999999999

test:
  commands:
    - echo "it installs!"

about:
  home: http://www.infradead.org/~tgr/libnl/
  license: LGPLv2
  license_family: LGPL
  license_file: libnl3-license
  summary: (CDT) Libraries and headers for using libnl3
  description: |
    This package contains various headers for using libnl3

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
