package:
  name: gtk2-cos6-x86_64
  version: 2.24.23

source:
  - url: https://vault.centos.org/6.10/os/x86_64/Packages/gtk2-2.24.23-9.el6.x86_64.rpm
    sha256: 901e61f1c5c2cdea5bdbc5ea54cdeac326a8817b4e42a3daaf706f3fcc289e24
    no_hoist: true
    folder: binary
  # - url: http://vault.centos.org/6.10/os/Source/SPackages/gtk2-2.24.23-9.el6.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int }}
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - atk-cos6-x86_64 >=1.29.4 *_{{ cdt_build_number|int }}
    - glib2-cos6-x86_64 >=2.28.0 *_{{ cdt_build_number|int }}
    - libx11-cos6-x86_64 >=1.5.0 *_{{ cdt_build_number|int }}
    - libxrandr-cos6-x86_64 >=1.2.99.4 *_{{ cdt_build_number|int }}
    - pango-cos6-x86_64 >=1.20.0 *_{{ cdt_build_number|int }}
  host:
    - atk-cos6-x86_64 >=1.29.4 *_{{ cdt_build_number|int }}
    - glib2-cos6-x86_64 >=2.28.0 *_{{ cdt_build_number|int }}
    - libx11-cos6-x86_64 >=1.5.0 *_{{ cdt_build_number|int }}
    - libxrandr-cos6-x86_64 >=1.2.99.4 *_{{ cdt_build_number|int }}
    - pango-cos6-x86_64 >=1.20.0 *_{{ cdt_build_number|int }}
  run:
    - atk-cos6-x86_64 >=1.29.4 *_{{ cdt_build_number|int }}
    - glib2-cos6-x86_64 >=2.28.0 *_{{ cdt_build_number|int }}
    - libx11-cos6-x86_64 >=1.5.0 *_{{ cdt_build_number|int }}
    - libxrandr-cos6-x86_64 >=1.2.99.4 *_{{ cdt_build_number|int }}
    - pango-cos6-x86_64 >=1.20.0 *_{{ cdt_build_number|int }}
  run_constrained:
    - sysroot_linux-64 ==99999999999

test:
  commands:
    - echo "it installs!"

about:
  home: http://www.gtk.org
  license: LGPL-2.0-or-later
  license_family: LGPL
  license_file: gtk2-copying
  summary: (CDT) The GIMP ToolKit (GTK+), a library for creating GUIs for X
  description: |
    GTK+ is a multi-platform toolkit for creating graphical user interfaces.
    Offering a complete set of widgets, GTK+ is suitable for projects ranging from
    small one-off tools to complete application suites.

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
