package:
  name: mesa-libgbm-devel-conda-x86_64
  version: 23.1.4

source:
  - url: https://vault.almalinux.org/9.3/AppStream/x86_64/os/Packages/mesa-libgbm-devel-23.1.4-1.el9.x86_64.rpm
    sha256: 14d8cb3b8181ca5ac1ebb800141e68cc8cfa611f00314c7f5016ba036d0af957
    no_hoist: true
    folder: binary
  # - url: https://vault.almalinux.org/9.3/AppStream/Source/Packages/mesa-23.1.4-1.el9.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int + 1000 }}
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - mesa-libgbm-conda-x86_64 ==23.1.4 *_{{ cdt_build_number|int + 1000 }}
  host:
    - mesa-libgbm-conda-x86_64 ==23.1.4 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-64 2.34.*
  run:
    - mesa-libgbm-conda-x86_64 ==23.1.4 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-64 2.34.*

test:
  commands:
    - echo "it installs!"

about:
  home: http://www.mesa3d.org
  license: MIT
  license_family: MIT
  license_file: mesa-license
  summary: (CDT) Mesa libgbm development package
  description: |
    Mesa libgbm development package.

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
