package:
  name: libnl3-devel-cos6-x86_64
  version: 3.2.21

source:
  - url: https://vault.centos.org/6.10/os/x86_64/Packages/libnl3-devel-3.2.21-8.el6.x86_64.rpm
    sha256: 7961489c21152e24aa78ce2e6a7f7699c137f2dc14c0cc0e6ca9c6a66446b37f
    no_hoist: true
    folder: binary
  # - url: http://vault.centos.org/6.10/os/Source/SPackages/libnl3-3.2.21-8.el6.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int + 1000 }}
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - libnl3-cos6-x86_64 ==3.2.21 *_{{ cdt_build_number|int + 1000 }}
    - libnl3-cli-cos6-x86_64 ==3.2.21 *_{{ cdt_build_number|int + 1000 }}
  host:
    - libnl3-cos6-x86_64 ==3.2.21 *_{{ cdt_build_number|int + 1000 }}
    - libnl3-cli-cos6-x86_64 ==3.2.21 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-64 2.12.*
  run:
    - libnl3-cos6-x86_64 ==3.2.21 *_{{ cdt_build_number|int + 1000 }}
    - libnl3-cli-cos6-x86_64 ==3.2.21 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-64 2.12.*

test:
  commands:
    - echo "it installs!"

about:
  home: http://www.infradead.org/~tgr/libnl/
  license: LGPLv2
  license_family: LGPL
  license_file: libnl3-license
  summary: (CDT) Libraries and headers for using libnl3
  description: |
    This package contains various headers for using libnl3

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
