package:
  name: pam-devel-cos7-aarch64
  version: 1.1.8

source:
  - url: https://vault.centos.org/altarch/7.9.2009/os/aarch64/Packages/pam-devel-1.1.8-23.el7.aarch64.rpm
    sha256: 25bff8e8908cfc0cd090472f6ab9732221fc0b8a003b7f15aeb29254198c9344
    no_hoist: true
    folder: binary
  # - url: http://vault.centos.org/altarch/7.9.2009/os/Source/SPackages/pam-1.1.8-23.el7.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int + 1000 }}
  noarch: generic
  binary_relocation: False
  detect_binary_files_with_prefix: False
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - pam-cos7-aarch64 ==1.1.8 *_{{ cdt_build_number|int + 1000 }}
  host:
    - pam-cos7-aarch64 ==1.1.8 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-aarch64 2.17.*
  run:
    - pam-cos7-aarch64 ==1.1.8 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-aarch64 2.17.*

test:
  commands:
    - echo "it installs!"

about:
  home: http://www.linux-pam.org/
  license: BSD and GPLv2+
  license_family: GPL2
  license_file: {{ SRC_DIR }}/binary/usr/share/doc/pam-devel-1.1.8/html/mwg-copyright.html
  summary: "(CDT) Files needed for developing PAM-aware applications and modules for PAM"
  description: |
        PAM (Pluggable Authentication Modules) is a system security tool that allows
        system administrators to set authentication policy without having to recompile
        programs that handle authentication. This package contains header files used
        for building both PAM-aware applications and modules for use with the PAM
        system.

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
