package:
  name: audit-libs-conda-x86_64
  version: 3.0.7

source:
  - url: https://vault.almalinux.org/8.9/BaseOS/x86_64/os/Packages/audit-libs-3.0.7-5.el8.x86_64.rpm
    sha256: 552ae323cd8de99295c0addc8f5dd0a2737f10d1f46c9f62f1bc7ce072c41841
    no_hoist: true
    folder: binary
  # - url: https://vault.almalinux.org/8.9/BaseOS/Source/Packages/audit-3.0.7-5.el8.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int + 1000 }}
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false
  missing_dso_whitelist:
    - '*'
  # this skip is here because we need different package hashes per distro.
  # we therefore list all possible values in CBC and skip those we don't want;
  # use in a selector ensures that the `distro` variable shows up in the hash
  skip: true  # [distro != "alma8"]

requirements:
  host:
    - sysroot_linux-64 2.28.*
  run:
    - sysroot_linux-64 2.28.*

test:
  commands:
    - echo "it installs!"

about:
  home: http://people.redhat.com/sgrubb/audit/
  license: LGPL-2.0-or-later
  license_family: LGPL
  license_file: audit-libs-copying.lib
  summary: (CDT) Dynamic library for libaudit
  description: |
    The audit-libs package contains the dynamic libraries needed for applications
    to use the audit framework.

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
