package:
  name: libpwquality-devel-alma8-x86_64
  version: 1.4.4

source:
  - url: https://vault.almalinux.org/8.9/PowerTools/x86_64/os/Packages/libpwquality-devel-1.4.4-6.el8.x86_64.rpm
    sha256: ad22bc7c947ef8d18a1396bc846768938854737ff2bad22eb0b9096167ddefd5
    no_hoist: true
    folder: binary
  # - url: https://vault.almalinux.org/8.9/PowerTools/Source/Packages/libpwquality-1.4.4-6.el8.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int + 1000 }}
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - libpwquality-alma8-x86_64 ==1.4.4 *_{{ cdt_build_number|int + 1000 }}
  host:
    - libpwquality-alma8-x86_64 ==1.4.4 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-64 2.28.*
  run:
    - libpwquality-alma8-x86_64 ==1.4.4 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-64 2.28.*

test:
  commands:
    - echo "it installs!"

about:
  home: https://github.com/libpwquality/libpwquality/
  license: BSD or GPLv2+
  license_family: GPL2
  license_file: libpwquality-copying
  summary: (CDT) Support for development of applications using the libpwquality library
  description: |
    Files needed for development of applications using the libpwquality library.
    See the pwquality.h header file for the API.

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
