package:
  name: xcb-util-image-cos6-x86_64
  version: 0.4.0

source:
  - url: https://vault.centos.org/6.10/os/x86_64/Packages/xcb-util-image-0.4.0-3.el6.x86_64.rpm
    sha256: 7153c414cc28c2a68bbc1b1ff8c2df8a16923566b5c13e93e7efdc947af4700a
    no_hoist: true
    folder: binary
  # - url: http://vault.centos.org/6.10/os/Source/SPackages/xcb-util-image-0.4.0-3.el6.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int }}
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false
  missing_dso_whitelist:
    - '*'

requirements:
  run_constrained:
    - sysroot_linux-64 ==99999999999

test:
  commands:
    - echo "it installs!"

about:
  home: http://xcb.freedesktop.org
  license: MIT
  license_family: MIT
  license_file: xcb-util-image-license
  summary: (CDT) Port of Xlib's XImage and XShmImage functions on top of libxcb
  description: |
    XCB util-image module provides the following library:    - image: Port of
    Xlib's XImage and XShmImage functions.

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
