package:
  name: audit-libs-cos7-x86_64
  version: 2.8.5

source:
  - url: http://mirror.centos.org/centos/7/os/x86_64/Packages/audit-libs-2.8.5-4.el7.x86_64.rpm
    sha256: 8531bf49043f146e7460e4f2bb898a7fa2ff1a07c70b9834d9cac60a3e3c57ed
    no_hoist: true
    folder: binary
  # - url: http://vault.centos.org/7.7.1908/os/Source/SPackages/audit-2.8.5-4.el7.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int + 1000 }}
  noarch: generic
  binary_relocation: False
  detect_binary_files_with_prefix: False
  missing_dso_whitelist:
    - '*'

requirements:
  host:
    - sysroot_linux-64 2.17.*
  run:
    - sysroot_linux-64 2.17.*

test:
  commands:
    - echo "it installs!"

about:
  home: http://people.redhat.com/sgrubb/audit/
  license: LGPL-2.0-or-later
  license_family: LGPL
  license_file: {{ SRC_DIR }}/binary/LICENSE_NOT_FOUND
  summary: "(CDT) Dynamic library for libaudit"
  description: |
        The audit-libs package contains the dynamic libraries needed for applications
        to use the audit framework.

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
