package:
  name: libibmad-devel-cos6-x86_64
  version: 1.3.11

source:
  - url: https://vault.centos.org/6.10/os/x86_64/Packages/libibmad-devel-1.3.11-1.el6.x86_64.rpm
    sha256: 81e096dc4ac9fe7e7c6cb4ef9ba2ea6220c3c4e1029cd0d71abdc22447243d5e
    no_hoist: true
    folder: binary
  # - url: http://vault.centos.org/6.10/os/Source/SPackages/libibmad-1.3.11-1.el6.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int + 1000 }}
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - libibmad-cos6-x86_64 ==1.3.11 *_{{ cdt_build_number|int + 1000 }}
  host:
    - libibmad-cos6-x86_64 ==1.3.11 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-64 2.12.*
  run:
    - libibmad-cos6-x86_64 ==1.3.11 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-64 2.12.*

test:
  commands:
    - echo "it installs!"

about:
  home: http://openfabrics.org/
  license: GPLv2 or BSD
  license_family: GPL2
  license_file:
    - libibmad-license
  summary: (CDT) Development files for the libibmad library
  description: |
    Development files for the libibmad library.

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
