package:
  name: audit-libs-conda-x86_64
  version: 3.0.7

source:
  - url: https://vault.almalinux.org/9.3/BaseOS/x86_64/os/Packages/audit-libs-3.0.7-104.el9.x86_64.rpm
    sha256: 7422f2e2811711681b7ba6bdf0ec5ba439b0187e750ee2d9171f08a30cf1eab6
    no_hoist: true
    folder: binary
  # - url: https://vault.almalinux.org/9.3/BaseOS/Source/Packages/audit-3.0.7-104.el9.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int + 1000 }}
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false
  missing_dso_whitelist:
    - '*'
  # this skip is here because we need different package hashes per distro.
  # we therefore list all possible values in CBC and skip those we don't want;
  # use in a selector ensures that the `distro` variable shows up in the hash
  skip: true  # [distro != "alma9"]

requirements:
  host:
    - sysroot_linux-64 2.34.*
  run:
    - sysroot_linux-64 2.34.*

test:
  commands:
    - echo "it installs!"

about:
  home: http://people.redhat.com/sgrubb/audit/
  license: LGPL-2.0-or-later
  license_family: LGPL
  license_file: audit-libs-copying.lib
  summary: (CDT) Dynamic library for libaudit
  description: |
    The audit-libs package contains the dynamic libraries needed for applications
    to use the audit framework.

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
