package:
  name: audit-libs-cos7-aarch64
  version: 2.8.5

source:
  - url: http://mirror.centos.org/altarch/7/os/aarch64/Packages/audit-libs-2.8.5-4.el7.aarch64.rpm
    sha256: c67ba5a600a6a94da1ee52fffc4855b6f6c75ae4ad1a568aafec1538849d8395
    no_hoist: true
    folder: binary
  # - url: http://vault.centos.org/7.7.1908/os/Source/SPackages/audit-2.8.5-4.el7.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int }}
  noarch: generic
  binary_relocation: False
  detect_binary_files_with_prefix: False
  missing_dso_whitelist:
    - '*'

requirements:
  run_constrained:
    - sysroot_linux-aarch64 ==99999999999

test:
  commands:
    - echo "it installs!"

about:
  home: http://people.redhat.com/sgrubb/audit/
  license: LGPL-2.0-or-later
  license_family: LGPL
  license_file: {{ SRC_DIR }}/binary/LICENSE_NOT_FOUND
  summary: "(CDT) Dynamic library for libaudit"
  description: |
        The audit-libs package contains the dynamic libraries needed for applications
        to use the audit framework.

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
