package:
  name: pam-cos7-aarch64
  version: 1.1.8

source:
  - url: http://mirror.centos.org/altarch/7/os/aarch64/Packages/pam-1.1.8-23.el7.aarch64.rpm
    sha256: 964b4395d6d2e7420793e8b9ea1688d2d07ae5a2f4b2455ef239f9f026cc74b3
    no_hoist: true
    folder: binary
  # - url: http://vault.centos.org/7.7.1908/os/Source/SPackages/pam-1.1.8-23.el7.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int + 1000 }}
  noarch: generic
  binary_relocation: False
  detect_binary_files_with_prefix: False
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - audit-libs-cos7-aarch64 >=1.0.8 *_{{ cdt_build_number|int + 1000 }}
    - cracklib-dicts-cos7-aarch64 >=2.8 *_{{ cdt_build_number|int + 1000 }}
    - glibc-cos7-aarch64 >=2.3.90 *_{{ cdt_build_number|int + 1000 }}
    - libpwquality-cos7-aarch64 >=0.9.9 *_{{ cdt_build_number|int + 1000 }}
    - libselinux-cos7-aarch64 >=1.33.2 *_{{ cdt_build_number|int + 1000 }}
  host:
    - audit-libs-cos7-aarch64 >=1.0.8 *_{{ cdt_build_number|int + 1000 }}
    - cracklib-dicts-cos7-aarch64 >=2.8 *_{{ cdt_build_number|int + 1000 }}
    - glibc-cos7-aarch64 >=2.3.90 *_{{ cdt_build_number|int + 1000 }}
    - libpwquality-cos7-aarch64 >=0.9.9 *_{{ cdt_build_number|int + 1000 }}
    - libselinux-cos7-aarch64 >=1.33.2 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-aarch64 2.17.*
  run:
    - audit-libs-cos7-aarch64 >=1.0.8 *_{{ cdt_build_number|int + 1000 }}
    - cracklib-dicts-cos7-aarch64 >=2.8 *_{{ cdt_build_number|int + 1000 }}
    - glibc-cos7-aarch64 >=2.3.90 *_{{ cdt_build_number|int + 1000 }}
    - libpwquality-cos7-aarch64 >=0.9.9 *_{{ cdt_build_number|int + 1000 }}
    - libselinux-cos7-aarch64 >=1.33.2 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-aarch64 2.17.*

test:
  commands:
    - echo "it installs!"

about:
  home: http://www.linux-pam.org/
  license: BSD and GPLv2+
  license_family: GPL2
  license_file: {{ SRC_DIR }}/binary/usr/share/doc/pam-1.1.8/html/sag-copyright.html
  summary: "(CDT) An extensible library which provides authentication for applications"
  description: |
        PAM (Pluggable Authentication Modules) is a system security tool that allows
        system administrators to set authentication policy without having to recompile
        programs that handle authentication.

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
