package:
  name: opensm-cos7-aarch64
  version: 3.3.21

source:
  - url: http://mirror.centos.org/altarch/7/os/aarch64/Packages/opensm-3.3.21-3.el7_8.aarch64.rpm
    sha256: e096ca2e3f6f7dab71c74927e4140bc2d841e3bd241ebcacd19a17563b735bfd
    no_hoist: true
    folder: binary
  # - url: http://vault.centos.org/7.7.1908/os/Source/SPackages/opensm-3.3.21-3.el7_8.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int }}
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - opensm-libs-cos7-aarch64 ==3.3.21 *_{{ cdt_build_number|int }}
  host:
    - opensm-libs-cos7-aarch64 ==3.3.21 *_{{ cdt_build_number|int }}
  run:
    - opensm-libs-cos7-aarch64 ==3.3.21 *_{{ cdt_build_number|int }}
  run_constrained:
    - sysroot_linux-aarch64 ==99999999999

test:
  commands:
    - echo "it installs!"

about:
  home: https://github.com/linux-rdma/opensm
  license: GPLv2 or BSD
  license_family: GPL2
  license_file:
    - opensm-license
  summary: (CDT) OpenIB InfiniBand Subnet Manager and management utilities
  description: |
    OpenSM is the OpenIB project's Subnet Manager for Infiniband networks. The
    subnet manager is run as a system daemon on one of the machines in the
    infiniband fabric to manage the fabric's routing state.  This package also
    contains various tools for diagnosing and testing Infiniband networks that can
    be used from any machine and do not need to be run on a machine running the
    opensm daemon.

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
