package:
  name: mesa-dri-drivers-cos7-aarch64
  version: 18.3.4

source:
  - url: http://mirror.centos.org/altarch/7/os/aarch64/Packages/mesa-dri-drivers-18.3.4-10.el7.aarch64.rpm
    sha256: c8cd7f6759d26246b59adbc8ba958dd4a82f09e24e2a268a1cb4b9f3f34cec3f
    no_hoist: true
    folder: binary
  # - url: http://vault.centos.org/7.7.1908/os/Source/SPackages/mesa-18.3.4-10.el7.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int + 1000 }}
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - libdrm-cos7-aarch64 >=2.4.83 *_{{ cdt_build_number|int + 1000 }}
  host:
    - libdrm-cos7-aarch64 >=2.4.83 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-aarch64 2.17.*
  run:
    - libdrm-cos7-aarch64 >=2.4.83 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-aarch64 2.17.*

test:
  commands:
    - echo "it installs!"

about:
  home: http://www.mesa3d.org
  license: MIT
  license_family: MIT
  license_file: mesa-license
  summary: (CDT) Mesa-based DRI drivers
  description: |
    Mesa-based DRI drivers.

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
