package:
  name: kernel-headers-cos7-ppc64le
  version: 3.10.0

source:
  - url: http://mirror.centos.org/altarch/7/os/ppc64le/Packages/kernel-headers-3.10.0-1160.el7.ppc64le.rpm
    sha256: 6875ad8dbbf0cff85bf39bd2446ffb9e92de78e113496fba37fa5da9f10348b1
    no_hoist: true
    folder: binary
  # - url: http://vault.centos.org/7.7.1908/os/Source/SPackages/kernel-3.10.0-1160.el7.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int }}
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false
  missing_dso_whitelist:
    - '*'

requirements:
  run_constrained:
    - sysroot_linux-ppc64le ==99999999999

test:
  commands:
    - echo "it installs!"

about:
  home: http://www.kernel.org/
  license: GPL-2.0-only
  license_family: GPL2
  summary: (CDT) Header files for the Linux kernel for use by glibc
  description: |
    Kernel-headers includes the C header files that specify the interface between
    the Linux kernel and userspace libraries and programs.  The header files
    define structures and constants that are needed for building most standard
    programs and are also needed for rebuilding the glibc package.

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
