package:
  name: xorg-x11-server-common-cos6-x86_64
  version: 1.17.4

source:
  - url: https://vault.centos.org/6.10/os/x86_64/Packages/xorg-x11-server-common-1.17.4-17.el6.centos.x86_64.rpm
    sha256: eda900d7276fbd94ee9245a797d125823f3e8f6fba6a39de8f483bd74b5df178
    no_hoist: true
    folder: binary
  # - url: http://vault.centos.org/6.10/os/Source/SPackages/xorg-x11-server-1.17.4-17.el6.centos.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int }}
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - pixman-cos6-x86_64 >=0.30.0 *_{{ cdt_build_number|int }}
  host:
    - pixman-cos6-x86_64 >=0.30.0 *_{{ cdt_build_number|int }}
  run:
    - pixman-cos6-x86_64 >=0.30.0 *_{{ cdt_build_number|int }}
  run_constrained:
    - sysroot_linux-64 ==99999999999

test:
  commands:
    - echo "it installs!"

about:
  home: http://www.x.org
  license: MIT
  license_family: MIT
  license_file: x11-license
  summary: (CDT) Xorg server common files
  description: |
    Common files shared among all X servers.

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
