package:
  name: numactl-cos7-ppc64le
  version: 2.0.12

source:
  - url: http://mirror.centos.org/altarch/7/os/ppc64le/Packages/numactl-2.0.12-5.el7.ppc64le.rpm
    sha256: 188d558d22ab46eacd64b29fad9d115012a39481d2a7c60198d33442c4766386
    no_hoist: true
    folder: binary
  # - url: http://vault.centos.org/7.7.1908/os/Source/SPackages/numactl-2.0.12-5.el7.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int }}
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false
  missing_dso_whitelist:
    - '*'

requirements:
  run_constrained:
    - sysroot_linux-ppc64le ==99999999999

test:
  commands:
    - echo "it installs!"

about:
  home: https://github.com/numactl/numactl
  license: GPL-2.0-only
  license_family: GPL2
  license_file:
    - numactl-copyright.txt
    - numactl-gpl2.txt
    - numactl-lgpl2.txt
  summary: (CDT) Library for tuning for Non Uniform Memory Access machines
  description: |
    Simple NUMA policy support. It consists of a numactl program to run other
    programs with a specific NUMA policy.

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
