package:
  name: systemd-cos7-aarch64
  version: 219

source:
  - url: http://mirror.centos.org/altarch/7/os/aarch64/Packages/systemd-219-78.el7.aarch64.rpm
    sha256: a1053023a03316139b711cd9a27fa1d44e0869816be630b118cce3a92679a2ad
    no_hoist: true
    folder: binary
  # - url: http://vault.centos.org/7.7.1908/os/Source/SPackages/systemd-219-78.el7.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int + 1000 }}
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - kmod-cos7-aarch64 >=18 *_{{ cdt_build_number|int + 1000 }}
    - centos-release-cos7-aarch64 >=7 *_{{ cdt_build_number|int + 1000 }}
    - systemd-libs-cos7-aarch64 ==219 *_{{ cdt_build_number|int + 1000 }}
  host:
    - kmod-cos7-aarch64 >=18 *_{{ cdt_build_number|int + 1000 }}
    - centos-release-cos7-aarch64 >=7 *_{{ cdt_build_number|int + 1000 }}
    - systemd-libs-cos7-aarch64 ==219 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-aarch64 2.17.*
  run:
    - kmod-cos7-aarch64 >=18 *_{{ cdt_build_number|int + 1000 }}
    - centos-release-cos7-aarch64 >=7 *_{{ cdt_build_number|int + 1000 }}
    - systemd-libs-cos7-aarch64 ==219 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-aarch64 2.17.*
test:
  commands:
    - echo "it installs!"

about:
  home: http://www.freedesktop.org/wiki/Software/systemd
  license: LGPLv2+ and MIT and GPLv2+
  license_family: GPL2
  license_file:
    - LICENSE.GPL2
    - LICENSE.LGPL2.1
    - LICENSE.MIT
  summary: (CDT) A System and Service Manager
  description: |
    systemd is a system and service manager for Linux, compatible with SysV and
    LSB init scripts. systemd provides aggressive parallelization capabilities,
    uses socket and D-Bus activation for starting services, offers on-demand
    starting of daemons, keeps track of processes using Linux cgroups, supports
    snapshotting and restoring of the system state, maintains mount and automount
    points and implements an elaborate transactional dependency-based service
    control logic. It can work as a drop-in replacement for sysvinit.

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
