package:
  name: librdmacm-cos6-x86_64
  version: 1.0.21

source:
  - url: https://vault.centos.org/6.10/os/x86_64/Packages/librdmacm-1.0.21-0.el6.x86_64.rpm
    sha256: 39887f875e4e34964d842a519805de08c39f198862f3dc4f81bb9b804660fa34
    no_hoist: true
    folder: binary
  # - url: http://vault.centos.org/6.10/os/Source/SPackages/librdmacm-1.0.21-0.el6.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int + 1000 }}
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false
  missing_dso_whitelist:
    - '*'

requirements:
  host:
    - sysroot_linux-64 2.12.*
  run:
    - sysroot_linux-64 2.12.*

test:
  commands:
    - echo "it installs!"

about:
  home: http://www.openfabrics.org/
  license: GPLv2 or BSD
  license_family: GPL2
  license_file: librdmacm-devel-license
  summary: (CDT) Userspace RDMA Connection Manager
  description: |
    librdmacm provides a userspace RDMA Communication Managment API.

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
