package:
  name: mesa-libegl-cos7-ppc64le
  version: 18.3.4

source:
  - url: http://mirror.centos.org/altarch/7/os/ppc64le/Packages/mesa-libEGL-18.3.4-10.el7.ppc64le.rpm
    sha256: 9e722d09265089ba1eb68b7ffd958d86cefe08cc143bee39ef846a95415ac756
    no_hoist: true
    folder: binary
  # - url: http://vault.centos.org/7.7.1908/os/Source/SPackages/mesa-18.3.4-10.el7.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int + 1000 }}
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - mesa-libgbm-cos7-ppc64le ==18.3.4 *_{{ cdt_build_number|int + 1000 }}
  host:
    - mesa-libgbm-cos7-ppc64le ==18.3.4 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-ppc64le 2.17.*
  run:
    - mesa-libgbm-cos7-ppc64le ==18.3.4 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-ppc64le 2.17.*

test:
  commands:
    - echo "it installs!"

about:
  home: http://www.mesa3d.org
  license: MIT
  license_family: MIT
  license_file: mesa-license
  summary: (CDT) Mesa libEGL runtime libraries
  description: |
    Mesa libEGL runtime libraries

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
