package:
  name: audit-libs-cos7-ppc64le
  version: 2.8.5

source:
  - url: http://mirror.centos.org/altarch/7/os/ppc64le/Packages/audit-libs-2.8.5-4.el7.ppc64le.rpm
    sha256: b098d6e8b8fb2fcfcf80c3b0b67ef19a9f74e379f64d174a75599d2f78e6c0f1
    no_hoist: true
    folder: binary
  # - url: http://vault.centos.org/7.7.1908/os/Source/SPackages/audit-2.8.5-4.el7.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int }}
  noarch: generic
  binary_relocation: False
  detect_binary_files_with_prefix: False
  missing_dso_whitelist:
    - '*'

requirements:
  run_constrained:
    - sysroot_linux-ppc64le ==99999999999

test:
  commands:
    - echo "it installs!"

about:
  home: http://people.redhat.com/sgrubb/audit/
  license: LGPL-2.0-or-later
  license_family: LGPL
  license_file: {{ SRC_DIR }}/binary/LICENSE_NOT_FOUND
  summary: "(CDT) Dynamic library for libaudit"
  description: |
        The audit-libs package contains the dynamic libraries needed for applications
        to use the audit framework.

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
