package:
  name: cracklib-devel-conda-x86_64
  version: 2.9.6

source:
  - url: https://vault.almalinux.org/8.9/PowerTools/x86_64/os/Packages/cracklib-devel-2.9.6-15.el8.x86_64.rpm
    sha256: 08f3fc9a80bfd0d2b840c30918226c3c5e9ba5a80859afe4807807e55175de1b
    no_hoist: true
    folder: binary
  # - url: https://vault.almalinux.org/8.9/PowerTools/Source/Packages/cracklib-2.9.6-15.el8.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int + 1000 }}
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - cracklib-conda-x86_64 ==2.9.6 *_{{ cdt_build_number|int + 1000 }}
  host:
    - cracklib-conda-x86_64 ==2.9.6 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-64 2.28.*
  run:
    - cracklib-conda-x86_64 ==2.9.6 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-64 2.28.*

test:
  commands:
    - echo "it installs!"

about:
  home: http://sourceforge.net/projects/cracklib/
  license: LGPL-2.0-or-later
  license_family: LGPL
  license_file: cracklib-copying.lib
  summary: (CDT) Development files needed for building applications which use cracklib
  description: |
    The cracklib-devel package contains the header files and libraries needed for
    compiling applications which use cracklib.

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
