package:
  name: kernel-headers-cos7-x86_64
  version: 3.10.0

source:
  - url: http://vault.centos.org/7.9.2009/os/x86_64/Packages/kernel-headers-3.10.0-1160.el7.x86_64.rpm
    sha256: 81b4e4f401d2402736ceba4627eaafd5b615c2cc45aa4d4f941ea79562045139
    no_hoist: true
    folder: binary
  # - url: http://vault.centos.org/7.9.2009/os/Source/SPackages/kernel-3.10.0-1160.el7.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int + 1000 }}
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false
  missing_dso_whitelist:
    - '*'

requirements:
  host:
    - sysroot_linux-64 2.17.*
  run:
    - sysroot_linux-64 2.17.*

test:
  commands:
    - echo "it installs!"

about:
  home: http://www.kernel.org/
  license: GPL-2.0-only
  license_family: GPL2
  summary: (CDT) Header files for the Linux kernel for use by glibc
  description: |
    Kernel-headers includes the C header files that specify the interface between
    the Linux kernel and userspace libraries and programs.  The header files
    define structures and constants that are needed for building most standard
    programs and are also needed for rebuilding the glibc package.

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
