package:
  name: cracklib-cos7-ppc64le
  version: 2.9.0

source:
  - url: http://mirror.centos.org/altarch/7/os/ppc64le/Packages/cracklib-2.9.0-11.el7.ppc64le.rpm
    sha256: 4d10872c9b9cb81b495349256791192eb843fc49feb9be66cb5a6c6c76b88428
    no_hoist: true
    folder: binary
  # - url: http://vault.centos.org/7.7.1908/os/Source/SPackages/cracklib-2.9.0-11.el7.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int }}
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false
  missing_dso_whitelist:
    - '*'

requirements:
  run_constrained:
    - sysroot_linux-ppc64le ==99999999999

test:
  commands:
    - echo "it installs!"

about:
  home: http://sourceforge.net/projects/cracklib/
  license: LGPL-2.0-or-later
  license_family: LGPL
  license_file: cracklib-copying.lib
  summary: (CDT) A password-checking library
  description: |
    CrackLib tests passwords to determine whether they match certain security-
    oriented characteristics, with the purpose of stopping users from choosing
    passwords that are easy to guess. CrackLib performs several tests on
    passwords: it tries to generate words from a username and gecos entry and
    checks those words against the password; it checks for simplistic patterns in
    passwords; and it checks for the password in a dictionary.  CrackLib is
    actually a library containing a particular C function which is used to check
    the password, as well as other C functions. CrackLib is not a replacement for
    a passwd program; it must be used in conjunction with an existing passwd
    program.  Install the cracklib package if you need a program to check users'
    passwords to see if they are at least minimally secure. If you install
    CrackLib, you will also want to install the cracklib-dicts package.

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
