package:
  name: libsepol-alma8-x86_64
  version: 2.9

source:
  - url: https://vault.almalinux.org/8.9/BaseOS/x86_64/os/Packages/libsepol-2.9-3.el8.x86_64.rpm
    sha256: 55bfbf557e668657b3d8e9b7389c9ec89944c9c21957eecb5e311a9d50a7708d
    no_hoist: true
    folder: binary
  # - url: https://vault.almalinux.org/8.9/BaseOS/Source/Packages/libsepol-2.9-3.el8.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int + 1000 }}
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false
  missing_dso_whitelist:
    - '*'

requirements:
  host:
    - sysroot_linux-64 2.28.*
  run:
    - sysroot_linux-64 2.28.*

test:
  commands:
    - echo "it installs!"

about:
  home: https://github.com/SELinuxProject/selinux/wiki
  license: LGPL-2.0-or-later
  license_family: LGPL
  license_file: libsepol-license
  summary: (CDT) SELinux binary policy manipulation library
  description: |
    Security-enhanced Linux is a feature of the Linux® kernel and a number of
    utilities with enhanced security functionality designed to add mandatory
    access controls to Linux.  The Security-enhanced Linux kernel contains new
    architectural components originally developed to improve the security of the
    Flask operating system. These architectural components provide general support
    for the enforcement of many kinds of mandatory access control policies,
    including those based on the concepts of Type Enforcement®, Role-based Access
    Control, and Multi-level Security.  libsepol provides an API for the
    manipulation of SELinux binary policies. It is used by checkpolicy (the policy
    compiler) and similar tools, as well as by programs like load_policy that need
    to perform specific transformations on binary policies such as customizing
    policy boolean settings.

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
